# coding=utf-8

"""Application constants."""


OR_SEPARATOR = "__OR__"

IS_NULL = "isnull"
IS_EMPTY = "isempty"
IS_TRUE = "istrue"
IS_FALSE = "isfalse"

FILTER_PARAMETER_NAME = "__model_filter"

FORM_SAVE_APPLY = "_saveapply"
FORM_SAVE_APPLY_DISCARD = "_applydiscard"

SETTING_MODEL_FILTERS_VIEW_OWNER_ONLY = "MODEL_FILTERS_VIEW_OWNER_ONLY"
DEFAULT_MODEL_FILTERS_VIEW_OWNER_ONLY = True

SETTING_MODEL_FILTERS_CHANGE_OWNER_ONLY = "MODEL_FILTERS_CHANGE_OWNER_ONLY"
DEFAULT_MODEL_FILTERS_CHANGE_OWNER_ONLY = True

SETTING_MODEL_FILTERS_DELETE_OWNER_ONLY = "MODEL_FILTERS_DELETE_OWNER_ONLY"
DEFAULT_MODEL_FILTERS_DELETE_OWNER_ONLY = True

SETTING_MODEL_FILTERS_ORDER_BY = "MODEL_FILTERS_ORDER_BY"

SETTING_MODEL_FILTERS_USE_GUARDIAN = "MODEL_FILTERS_USE_GUARDIAN"
DEFAULT_MODEL_FILTERS_USE_GUARDIAN = False

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
